  
name=Toggl API v9 - Arduino Implementation
version=1.9.0
author=Enrique Jorreto, Joey Strandnes
maintainer=Enrique Jorreto
sentence= Toggl API v9 implementation for ESP
paragraph= Easy to use port of Toggl API v9 with stripped functionality to efficiently work with the ESP family. Based on the v8 implementation from Joey Strandnes.
category=Communication
url=https://github.com/ejorreto/Arduino-Toggl-API
architectures=*
depends = ArduinoJson (>=7.0)